### PR TITLE
Enable the '/single' switch (#577)

### PR DESCRIPTION
**Pull request by DoCode**
Fixed issue #577

### CODE REVIEW

**Comment by vBm** [comment]
@DoCode since .cpp is using tabs and your patch is using spaces, maybe you should fix that and force-push that again (just to be consistent with rest of the code) ? :)

**Comment by DoCode** [comment]
if it is absolutely necessary;)

**Comment by MartiUK** [comment]
@DoCode CMDER_START is still not being set as of the latest development build.

**Comment by DoCode** [comment]
@MartiUK CMDER_START is set to Home when NOT in single mode
https://github.com/cmderdev/cmder/blob/development/vendor/profile.ps1#L105

**Pull request merged**
