### PR TITLE
Enable the '/single' switch (#577)

### PR DESCRIPTION
**Pull request by DoCode**
By using the registry as statemachine for the current location ('CMDER_START')
- SendMessageTimeout with WM_SETTINGCHANGE does not work in the same process

### CODE REVIEW

**Comment by Stanzilla** [comment]
Eh, can you do that again, without the whitespace changes?

**Comment by DoCode** [comment]
so now...

**Comment by Stanzilla** [comment]
and squash :p

**Comment by Stanzilla** [comment]
@DoCode Can you squash your commits, please?

**Comment by DoCode** [comment]
@Stanzilla Squashed :smile:

**Comment by vBm** [comment]
@DoCode not really squashed since there are still 5 commits :P

**Comment by DoCode** [comment]
Sorry...

I squashed it in one hour ;)

**Comment by MartiUK** [comment]
Any reason why you've changed the optimization settings in the `.vcxproj`?

**Comment by DoCode** [comment]
No, only for performance tests

**Comment by MartiUK** [comment]
@DoCode Ah cool, just noticed this is being pulled into master, would it be possible to re-pull to development? Thanks

**Pull request closed without merging**
