### PR TITLE
Add MinGW commands to path

### PR DESCRIPTION
**Pull request by gucong3000**

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
@daxgames This seems reasonable, but against the "Lib it" branch

**Comment by daxgames** [comment]
Not sure about this one.  Need to test it and and decide.  Probably will get added just not exactly like this.  Holding off for now to let some of the dust settle.

**Comment by DRSDavidSoft** [comment]
@daxgames @gucong3000 Also MinGW should **only** be added to path, if _vendored_ Git is decided to be used by `init.bat`.

**Comment by daxgames** [comment]
@DRSDavidSoft Vendored Git or user installed 'Git for Windows'.  Notice the code only adds it if the folder exists.

**Comment by daxgames** [comment]
@gucong3000 - I am adding this to my PR #1665 as it already has enhancements to how we update the path by adding this to my PR I can do it by adding 4 lines of code:

```
    if exist "!GIT_INSTALL_ROOT!\mingw32" (
        call :enhance_path "!GIT_INSTALL_ROOT!\mingw32" append
    ) else if exist "!GIT_INSTALL_ROOT!\mingw64"
        call :enhance_path "!GIT_INSTALL_ROOT!\mingw64" append
    )
```

**Pull request closed without merging**
