### PR TITLE
If user has his own powershell profile, use it

### PR DESCRIPTION
**Pull request by pavelkouril**
If user has his own `$PROFILE`, cmder should launch it after loading all its settings.

This allows user to set default directory/create new functions or aliases/etc. quite easily and have them available in both cmder and traditional powershell window.

### CODE REVIEW

**Comment by JanSchulz** [comment]
Is `$PROFILE" a standard way to extend a powershell console environment?

**Comment by pavelkouril** [comment]
http://www.howtogeek.com/50236/customizing-your-powershell-profile/
http://www.computerperformance.co.uk/powershell/powershell_profile_ps1.htm
https://technet.microsoft.com/en-us/magazine/2008.10.windowspowershell.aspx

Definitely looks like it.

**Comment by MartiUK** [comment]
Could you re-pull this into development please.

**Comment by Jackbennett** [comment]
There's actually 4 profiles to be aware of as my personal extensions reside within currentProfileAllHosts

`$profile | fl -Force`

Hosts being what program is playing host to the powershell session. E.g. 

Run `powershell.exe -noExit -command "Get-host"`
Run `Get-host` from within the powershell ISE you'll get a different name. And can have a different profile.

So this PR just needs checking against what files are called in which order depending on what the user has present.

**Comment by pavelkouril** [comment]
@MartiUK Hmm, so should I open different PR with another branch?

@Jackbennett So, what exactly should be changed? I'm sorry but my understanding of PS is kinda limited (I use it for basic scripting, mostly). If you either could explain what should be done differently (or prepare a more correct PR), it would be wonderful. :)

**Comment by MartiUK** [comment]
@pavelkouril Yes, please.

**Pull request closed without merging**
