### PR TITLE
Remove appveyor config

### PR DESCRIPTION
**Pull request by MartiUK**
We can create releases and upload build artefacts without the need of AppVeyor. I think we should switch it off.

This should be merged after #2804

Signed-off-by: Martin Kemp <me@martinke.mp>

### CODE REVIEW

**Review by Stanzilla — APPROVED** [review]

**Comment by DRSDavidSoft** [comment]
@MartiUK One problem was present when I was initially added the GH actions task:
https://github.com/cmderdev/cmder/pull/2725#issuecomment-1279594341

Without AppVeyor, all builds it seems will contain a ZIP file that contains another ZIP file in it

**Comment by MartiUK** [comment]
Unfortunately, nothing we can do about the double zipping of artefacts, perhaps it'll be better to upload to something like s3?

I'm happy to pay for Cloudflare r2, as the cmder.app domain is under Cloudflare at the moment. It means we can include a pre-release build on the site as well.

**Comment by DRSDavidSoft** [comment]
Ah, I wish we kept AppVeyor for now, GitHub actions is still building double ZIP files https://github.com/cmderdev/cmder/pull/2725#issuecomment-1279594341) - try downloading artifcats from here:
https://github.com/cmderdev/cmder/actions/runs/5611280395

Maybe this issue has been solved since I initially implemented GitHub actions, but I haven't had time to investigate or rewrite the action scripts.  Would you vote to still remove AppVeyor if the issue with GH actions is still present?

---

**Update 2026:** Fixed in #3075! 🥳

**Comment by Stanzilla** [comment]
> Ah, I wish we kept AppVeyor for now, GitHub actions is still building double ZIP files [#2725 (comment)](https://github.com/cmderdev/cmder/pull/2725#issuecomment-1279594341)) - try downloading artifcats from here: [cmderdev/cmder/actions/runs/5611280395](https://github.com/cmderdev/cmder/actions/runs/5611280395)
> 
> Maybe this issue has been solved since I initially implemented GitHub actions, but I haven't had time to investigate or rewrite the action scripts. Would you vote to still remove AppVeyor if the issue with GH actions is still present?

Nah, they still think that is working as intended

**Comment by DRSDavidSoft** [comment]
Hey @Stanzilla long time no see! Sorry, do you mean they as GitHub or @MartiUK?

Can I also have everyone's opinion on what should the CI prepare for our users? Personally, I am against double compression. It doesn't make sense to me for the CI to give users a ZIP file that contains a 7Z file inside it. I couldn't figure out a way to bypass this back when I implemented GitHub actions.

Options:

- Leave it as is, forgo AppVeyor
- Remove 7Z files (I'm against this as well personally)
- Bring back AppVeyor (or any other CI that provides raw 7Z file as is)
- Investigate GitHub actions to fix this issue

**Comment by MartiUK** [comment]
As I said earlier I'm happy to throw some cash in to upload our archives into Cloudflare R2 for the website and our GH releases to link to.

**Comment by DRSDavidSoft** [comment]
@MartiUK Thanks, we just need to somehow implement it. I'm busy at the moment, but if you have any links to a documentation please share so I can take a look and see if I can implement it. Hopefully it's easy to do.

**Pull request merged**
