### PR TITLE
Reorganize how clink settings are loaded

### PR DESCRIPTION
**Pull request by JanSchulz**
4bfdf04d59dab80e1ce76d7125c546006273e188 moved all clink config files
to vendor/ and therefore the files in config/ were not used and .history
was also moved to vendor/.

The new arrangement uses `--script` to load our own clink.lua file which in
turn as the first thing loads the original clink.lua file. The user defined
files are again in config/. As clink regenerates these files, if they are not
present, this also means that we don't need to include the settings file
in the git repo and therefore don't overwrite it on updates.

Closes: https://github.com/cmderdev/cmder/issues/793

### CODE REVIEW

**Comment by JanSchulz** [comment]
Just a note: the current setup is broken as it places the clink files (mainly `history` and `settings`) in `vendor\` and not in `config\`.

**Comment by JanSchulz** [comment]
ping?

**Comment by MartiUK** [comment]
I need to figure this out, a lot of contradicting PRs and changes.

**Comment by Stanzilla** [comment]
@MartiUK why not just merge this? Other PRs have to be rebased on that but this at least fixes the problem, no?

**Comment by MartiUK** [comment]
Fair enough

**Pull request merged**
