### PR TITLE
Fix icons

### PR DESCRIPTION
**Pull request by daxgames**
Added Git for Windows icon to mintty tasks to differentiate them from 100% supported Cmder tasks

Get 100% supported Cmder task icons from icons\Cmder.ico so tabs have an ico if launched from the cmder.bat file

### CODE REVIEW

**Comment by Stanzilla** [comment]
Was the current way of trying to get the icon from the exe not working?

**Comment by daxgames** [comment]
It would probably work fine if I could build the cmder.exe but I can't because I do not have the tools.  I and anyone else trying/developing on the dev branch that cannot build the exe use the cmder.bat to start cmder.

I just did what I did so it would work all the time with or without the cmder.exe.  To me working all the time was better than working some of the time even if the cmder.bat is deprecated.

**Comment by Stanzilla** [comment]
Makes sense

**Comment by MartiUK** [comment]
Any possibility of moving that last commit to a separate pull request? It has nothing to do with fixing the icons :smile:

**Comment by daxgames** [comment]
Sure.  Will do later today.

**Comment by daxgames** [comment]
Done

**Comment by MartiUK** [comment]
Thanks.

**Pull request merged**
