### PR TITLE
Fix build system scripts (closes #2723)

### LINKED ISSUE #2723: Cmder build is failing
@cmderdev/core @cmderdev/trusted-contributors anyone know how to fix this.

image

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
### Description
This PR updates some build properties in order to fix both the AppVeyor builds and also the build scripts running on a local machine.

I plan to work on a GitHub Actions PR in order to either replace AppVeyor or run GitHub Actions alongside it.

### Note
Please first merge the following PRs, as this one contains commits from those as well:
- #2746
- #2747 

### Status
Closes #2723

Thanks! 😄

### CODE REVIEW

**Comment by daxgames** [comment]
@DRSDavidSoft Thanks and merged.

**Comment by daxgames** [comment]
@DRSDavidSoft build is still failing. although it worked fine for me on my local system.

@MartiUK any changes required for the appveyor job that I think you own to make these changes work to fix the build scripts.

**Comment by daxgames** [comment]
@DRSDavidSoft ???
@MartiUK  ???

**Comment by DRSDavidSoft** [comment]
@daxgames I think it's time to add me as the cmder core dev teams.  I'd like to ask for the same permissions as a maintainer, and also to the AppVeyor CI dashboard.  I'll fix everything as needed in order to make the build system functional again.

Also, please give me permissions so I can set up GitHub actions, and also update issues templates.

Other than that, the build system is working on my forks:
https://ci.appveyor.com/project/DRSDavidSoft/cmder

**Comment by daxgames** [comment]
@DRSDavidSoft I don't even have access to the appveyor stuff that is why I asked @MartiUK about it.

While I am the currently the most active here I don't know if it is my call to give the access you request.  If the rest of the @cmderdev/trusted-contributors agree I am all for it.

**Comment by MartiUK** [comment]
@DRSDavidSoft Apologies, I thought you already were a trusted contributor. I've invited you, you're welcome to continue on with the changes to appveyor etc.

**Comment by DRSDavidSoft** [comment]
@MartiUK Thanks for granting the permission, I already created the GitHub Actions workflow for building Cmder (more in https://github.com/cmderdev/cmder/pull/2725#issuecomment-1279594341).   However, there is still an issue with AppVeyor:

I have yet again limited functionality to apply adjustments to the repo's CI settings (beside GitHub actions), and I don't have access to the AppVeyor settings (in the MartiUK account):

### https://ci.appveyor.com/project/MartiUK/cmder

> image

### https://ci.appveyor.com/project/DRSDavidSoft/cmder

For reference, the same `appveyor.yml` config file and the same repo builds correctly on my AppVeyor instance:

Image


I would appreciate it if you could either grant me access to your fork of Cmder on AppVeyor, or change **Environment** → **Build worker image** to **Visual Studio 2019**, or allow me to use `appveyor.com/project/DRSDavidSoft` instead of `appveyor.com/project/MartiUK` in the cmder repo.

This will require adding back the AppVeyor marketplace app to the GitHub repo, which I'd appreciate if either you could do it, or grant me the required permissions in order for me to install it.

Thanks! 👍🏻

**Comment by DRSDavidSoft** [comment]
@MartiUK I would also appreciate it if you could send an screenshot of the following settings in your AppVeyor panel:

image

**Comment by daxgames** [comment]
It would be great if we all had access tonthe Appveyor stuff if possible.

**Comment by DRSDavidSoft** [comment]
@daxgames There is documentation regarding how to set up an organization with proper access to team mebers:
https://www.appveyor.com/docs/team-setup/

**Comment by DRSDavidSoft** [comment]
Tracking in #2734

**Comment by MartiUK** [comment]
I've enabled team access to appveyor, hopefully you guys can just login with github on appveyor and you'll have access

**Comment by MartiUK** [comment]
> @MartiUK I would also appreciate it if you could send an screenshot of the following settings in your AppVeyor panel:
> 
> image

They are exactly as you have them there

**Comment by MartiUK** [comment]
> @MartiUK Thanks for granting the permission, I already created the GitHub Actions workflow for building Cmder (more in [#2725 (comment)](https://github.com/cmderdev/cmder/pull/2725#issuecomment-1279594341)). However, there is still an issue with AppVeyor:
> 
> I have yet again limited functionality to apply adjustments to the repo's CI settings (beside GitHub actions), and I don't have access to the AppVeyor settings (in the MartiUK account):
> 
> ###  https://ci.appveyor.com/project/MartiUK/cmder
> > image
> 
> ###  https://ci.appveyor.com/project/DRSDavidSoft/cmder
> For reference, the same `appveyor.yml` config file and the same repo builds correctly on my AppVeyor instance:
> 
> Image
> 
> I would appreciate it if you could either grant me access to your fork of Cmder on AppVeyor, or change **Environment** → **Build worker image** to **Visual Studio 2019**, or allow me to use `appveyor.com/project/DRSDavidSoft` instead of `appveyor.com/project/MartiUK` in the cmder repo.
> 
> This will require adding back the AppVeyor marketplace app to the GitHub repo, which I'd appreciate if either you could do it, or grant me the required permissions in order for me to install it.
> 
> Thanks! 👍🏻

Set worker image to VS 2019

**Comment by DRSDavidSoft** [comment]
image

Unfortunately, now no one can access the project (signed-in or signed-out):
https://ci.appveyor.com/project/MartiUK/cmder

**Comment by MartiUK** [comment]
It has been renamed to: https://ci.appveyor.com/project/cmderdev/cmder

**Pull request merged**
