### PR TITLE
Added Context Menu with flexible ConEmu params

### PR DESCRIPTION
**Pull request by sheikhmishar**
I have added support for custom Context Menu, where predefined Task can be started on clicking "Terminal Here".
Also, it adds support for passing params to ConEmu, which can be utilized to use the whole ConEmu ecosystem

### CODE REVIEW

**Comment by sheikhmishar** [comment]
@daxgames  Thank you for your review. In short, I wanted to integrate ConEmu args without reimplementing those to Cmder. However, from your review, I got the flaw of my approach. -- [ conemu args ] was unknown to me as well.

**Comment by daxgames** [comment]
What Conemu args are you wanting to pass to EVERY shell extension launch of Cmder on a directory or a drive?

It seems like overkill to me but I don't know what you are trying to do beyond sharing a pre-existing Cmder window with shell extension launched sessions and this is already possible.

**Comment by daxgames** [comment]
Closing this PR because everything in this PR is already supported by the existing functionality without hard coding anything into the launcher.

1. Create the `CmderXtra.reg` file below.
2. Import it.
3. Try out the shell extension.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\Directory\Background\shell\ConEmu_Cmder]
@="ConEmu/Cmder Here"
"NoWorkingDirectory"=""
"Icon"="C:\\Users\\vagrant\\cmderdev\\icons\\cmder_red.ico"

[HKEY_CLASSES_ROOT\Directory\Background\shell\ConEmu_Cmder\command]
@="\"C:\\Users\\vagrant\\cmderdev\\Cmder.exe\" -- -reuse -run {cmd::Cmder} -new_console:d:\"%V\":t:\"ConEmu - Cmder\" "

[HKEY_CLASSES_ROOT\Directory\shell\ConEmu_Cmder]
@="ConEmu/Cmder Here"
"NoWorkingDirectory"=""
"Icon"="C:\\Users\\vagrant\\cmderdev\\icons\\cmder_red.ico"

[HKEY_CLASSES_ROOT\Directory\shell\ConEmu_Cmder\command]
@="\"C:\\Users\\vagrant\\cmderdev\\Cmder.exe\" -- -reuse -run {cmd::Cmder} -new_console:d:\"%V\":t:\"ConEmu - Cmder\" "

[HKEY_CLASSES_ROOT\Drive\Background\shell\ConEmu_Cmder]
@="ConEmu/Cmder Here"
"NoWorkingDirectory"=""
"Icon"="C:\\Users\\vagrant\\cmderdev\\icons\\cmder_red.ico"

[HKEY_CLASSES_ROOT\Drive\Background\shell\ConEmu_Cmder\command]
@="\"C:\\Users\\vagrant\\cmderdev\\Cmder.exe\" -- -run {cmd::Cmder} -new_console:d:\"%V\""t:\"ConEmu - Cmde\" "

[HKEY_CLASSES_ROOT\Drive\shell\ConEmu_Cmder]
@="ConEmu/Cmder Here"
"NoWorkingDirectory"=""
"Icon"="C:\\Users\\vagrant\\cmderdev\\icons\\cmder_red.ico"

[HKEY_CLASSES_ROOT\Drive\shell\ConEmu_Cmder\command]
@="\"C:\\Users\\vagrant\\cmderdev\\Cmder.exe\" -- -reuse -run {cmd::Cmder} -new_console:d:\"%V\":t:\"ConEmu - Cmder\" "
```

**Comment by daxgames** [comment]
I also added the above to the [Wiki](https://github.com/cmderdev/cmder/wiki/Context-menu-integration#advanced-shell-extension-setup)

**Comment by daxgames** [comment]
@DRSDavidSoft How do I make Changes to `strings.rc2` appear in the compiles `Cmder.exe`?

I have changed the below:

`/m\n    /x [ConEmu extra arguments]\n\nor,`

to:

`/m\n    -- [ConEmu extra arguments]\n\nNote: '-- [...]' must be the last argument!\n\nor,`

because `-- [ConEmu extra arguments]` is undocumenrted, works better and `/x [ConEmu extra arguments]` NEEDS to go away.

**Comment by DRSDavidSoft** [comment]
@daxgames Hi, are you using the scripts to build the project, manually invoking the msbuild, or using the build button in VS?

If you use the build scripts, it will invoke "clean" to remove cached items, and will copy any necessary template files to the required directories.

Additionally you can push to a branch and have GH Actions or Appveyor CI build it

If none of these helped, please attach your current build configuration on a new discussions issue and tag me, I'll check as soon as possible

Also sorry I've been busy with some issues so I haven't had time yet to review other PRs as well, I'll check them soon too. Thanks

**Comment by daxgames** [comment]
I don't know what was happening it seems fine now.

I used the scripts, I also tried to build a release from inside visual studio.  I don't know what I did to fix it.

The optimize for speed PR is pretty cool and it increases the speed drastically.  That is the one I really want to get merged.

**Pull request closed without merging**
