### PR TITLE
use /dir Switch instead of CMDER_START

### PR DESCRIPTION
**Pull request by david-driscoll**
So I've been trying to use `/single <path>` to open a new console, in an existing cmder instance.  And currently it's not working.  At first I thought it was because the environment variable wasn't be set (it was).

I think I've nailed down the scenario that's the problem... I unfortunately don't have VS2015 and and friends installed on this machine, so I will review this later tonight as well.

When opening a new instance of Cmder `Cmder.exe /single C:\`.  `CMDER_START` is set properly, and the folder is correct.

When trying to open another instance of Cmder `Cmder.exe /single C:\` the directory always defaults to   `%USERPROFILE%`.  Now this is because the directory is set for the new console from `ConEmu`.  In this scenario what appears to be happening is that the Environment Variable `CMDER_START` on the original `Cmder` instance (which is a wrapper for `ConEmu`?) will not be changed or set when `/single` is called.

I believe this value can be set via the `/dir` switch on ConEmu itself, so this change is an attempt to do that.

As I said I don't have the tool chain installed on this machine to really test the changes, and if this change is completely off base feel free to let me know.

### CODE REVIEW

**Comment by Stanzilla** [comment]
Can probably loop in @Maximus5 to confirm that

**Comment by Maximus5** [comment]
I have no idea, how `/single` in cmder is implemented.

Empty switch `-new_console` in Tasks is useless.

Using `%CMDER_ROOT%` in profile initialization scripts is bad idea - they would fail if user starts just a `ConEmu.exe`.

**Comment by Stanzilla** [comment]
Okay, thanks for your input!

**Comment by janschulz** [comment]
> When trying to open another instance of Cmder Cmder.exe /single C:\ the directory always defaults to %USERPROFILE%. Now this is because the directory is set for the new console from ConEmu. In this scenario what appears to be happening is that the Environment Variable CMDER_START on the original Cmder instance (which is a wrapper for ConEmu?) will not be changed or set when /single is called.

Somehow this sounds like a bug and maybe it is easier to find out why in that case CMDER_START is not set?

**Comment by david-driscoll** [comment]
Well the `CMDER_START` environment variable belonges to the other process (the first copy of Cmder that was started).  So when you say `cmder /single <path>`

So the basic example of the issue, from any command prompt (just plain old `cmd`), with Cmder closed.

Run:

```
cmder /single c:\
cmder /single c:\windows
cmder /single
```

In all three cases the default directory will be `C:\` because, the original, and `single` host process always has the same default environment variable for `CMDER_START` set.  You can repeat it doing `/single` first, and then the default will always be `%USERPROFILE%`.

With these changes, now that I've dusted off my C++ (It's been a long while forgive me!).  All of the above commands open as expected, to the correct directory.

Let me know if you need more information or details!

**Comment by janschulz** [comment]
Ok, do I understand that right, that if I start cmder via an icon, the conemu process has no `CMDER_START` env variable. When I then start another `cmder /single C:`, this sets `CMDER_START` in the current process and starts a new conemu (which also still has that set), but this will find another conemu already running and passes control to that instance, but that instance has no `CMDER_START` set, so the started new child cmd will also not have it?

If so we have to look for another way to do this...

The normal startup (as far as I thought when I worked on the launcher code for `CMDER_START`) should have all this properties (in decreasing priority: first condition satisfied will win):

* If the user specifies any dir to `cmder <path>`, it should startup in that path
* if the user has specified `CMDER_START` as env variable, it should startup there
* If the user sets a startup parameter in the ConEmu task spec, it should startup there.
* The normal startup without any parameter and nothing set should startup in %USERPROFILE%

>  I unfortunately don't have VS2015 and and friends installed on this machine, so I will review this later tonight as well.

You can download the built cmder form appveyor -> just follow the link in the "checks" to appveyor and there to the artefacts.

**Comment by janschulz** [comment]
> Using %CMDER_ROOT% in profile initialization scripts is bad idea - they would fail if user starts just a ConEmu.exe.

How should we work around that? The only thing I can think of is using `ConEmuDir` env var to compute CMDER_ROOT in each startup script...?

**Comment by david-driscoll** [comment]
I have VS2015 on my home laptop and surface, just not on my work machine.  So I was able to get it it work.

With this PR currently it does:

* If the user specifies any dir to cmder <path>, it should startup in that path
* The normal startup without any parameter and nothing set should startup in %USERPROFILE%

> If the user sets a startup parameter in the ConEmu task spec, it should startup there.
I'm not sure if their task spec `/dir` would override the one provided by `Cmder`



I could add a step before `USERPOFILE` that looks for `CMDER_START`.  I just wonder how much value is the environment variable `CMDER_START`?

**Comment by janschulz** [comment]
>  I just wonder how much value is the environment variable CMDER_START?

I wouldn't mind if it is gone... But others have to decide this.

What makes this issue interesting is that if both CMDER_START and CMDER_ROOT would go away, there is IMO not much reason to keep the launcher around compared to using conemu directly... The only thing would be the copying of conemu config files on different machines...

**Comment by MartiUK** [comment]
@david-driscoll Can you resolve the conflicts, I'll review and merge when that's done.

**Comment by Jackbennett** [comment]
Only done some cursory reading (because I'm tired of looking at the word "single" haha) but this sounds like it might be worth looking through #420 and friends to make sure various things are accounted for.

**Comment by Stanzilla** [comment]
continue here https://github.com/cmderdev/cmder/pull/1609

**Pull request closed without merging**
