### PR TITLE
Improvement for user-prompt load in PS

### PR DESCRIPTION
**Pull request by NoNaNy**
Checking if the prompt variables are null o string empty (defined) for don't overwrite them.
Moved the lambda symbol to CmdPrompt for really to user let overwrite. And removed the double space after this symbol.

### CODE REVIEW

**Comment by daxgames** [comment]
Resolved merge conflict caused by merging #2193

**Comment by daxgames** [comment]
@NoNaNy All this really does at this time is makes changing the `λ` to another character.  #2193 fixed the Cmder prompt components in a better way so it was merged first.  Please test and make sure it still works for you as you intended.

**Comment by daxgames** [comment]
@NoNaNy and thanks for the PR!

**Comment by NoNaNy** [comment]
Yes this issue was fixed with the PR #2193

**Pull request closed without merging**
