### PR TITLE
vscode.bat

### PR DESCRIPTION
**Pull request by SupinePandora43**
add that to settings.json

```
"terminal.integrated.shell.windows": "cmd.exe",
"terminal.integrated.shellArgs.windows": [
    "/K",
    "%CMDER_ROOT%/vendor/bin/vscode_init.cmd",
]
```

for using cmder inside vscode.

simple .bat for starting init.bat if user manually opened console, and starting cmd.exe for task support

### CODE REVIEW

**Comment by daxgames** [comment]
@SupinePandora43 Does this address the cmder not working correctly with vscode tasks?

**Comment by SupinePandora43** [comment]
@daxgames  when you run task using cmder's init.bat, cmder will just start terminal with `/d` argument!

**Comment by daxgames** [comment]
Thats what i thought, thanks.

**Comment by SupinePandora43** [comment]
any review ?!

**Comment by daxgames** [comment]
@SupinePandora43  Could you please move the file to `%cmder_root%/vendor/bin/vscode_init.cmd` and update the pr comment to reflect the new path.  We keep all scripts owned by cmder in `%cmder_root%/vendor/bin`

**Comment by SupinePandora43** [comment]
@daxgames  done!

**Comment by SupinePandora43** [comment]
thanks!

**Pull request merged**
