### PR TITLE
Fix typos found by codespell

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by daxgames** [comment]
Thanks for pointing these out.  Closing, favoring more target changes.

**Comment by DimitriPapadopoulos** [comment]
Yes, just realized you do not want external contributions.

There are a few typos left after #2646 / #2647 :
```
./CHANGELOG.md:317: useage ==> usage
./CHANGELOG.md:318: varible ==> variable
./CHANGELOG.md:318: useage ==> usage
./CHANGELOG.md:329: build-in ==> built-in
./CHANGELOG.md:447: lamda ==> lambda
./CHANGELOG.md:604: Enconding ==> Encoding
./CHANGELOG.md:712: Cant ==> Can't
./CHANGELOG.md:850: Cant ==> Can't
./CHANGELOG.md:911: specail ==> special
./CHANGELOG.md:912: allready ==> already, all ready
./CHANGELOG.md:973: cant ==> can't
./launcher/src/version.rc2.sample:4: genereted ==> generated
```

**Comment by daxgames** [comment]
External contributions are fine.  Just not concerned with spelling errors in other peoples comments included in the changelog.

**Comment by DimitriPapadopoulos** [comment]
Well, you did end up adding my contribution under your own name.

**Comment by daxgames** [comment]
And I just gave ypu credit.  Was not trying to steal your thunder.

**Comment by daxgames** [comment]
I just didn't wantto ask you to remove the changelog.md edits.  Figured I could grt it done quicker myself.

**Comment by DimitriPapadopoulos** [comment]
No worries, this was a very minor contribution anyway. It's just that I had a hard time understanding the process and its outcome - rejected or modified PR.

**Pull request closed without merging**
