### PR TITLE
Fix the git command to obtain the dirty state of the repository

### LINKED ISSUE #928: git (dirty) repository status not shown in promtp since 1.3.0pre
I'm not getting the indicator of a dirty repo in the prompt since I updated to 1.3.0pre.

The command I think it's getting executed is `git diff --quiet --ignore-submodules HEAD 2>nul` but in my current instalattion returns:

```
fatal: ambiguous argument '2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I'll try to obtain a command that works and commit it as a fix later.

### PR DESCRIPTION
**Pull request by sveggiani**
Fixes #928

### CODE REVIEW

**Comment by luisrudge** [comment]
I can confirm this is now working:
image

**Comment by Stanzilla** [comment]
We had a few problems with os.execute which is why we switched away from it https://github.com/cmderdev/cmder/issues/749

Does this help you maybe? https://github.com/cmderdev/cmder/issues/809#issuecomment-207203013

**Comment by sveggiani** [comment]
@Stanzilla nope, it doesn't work. I'll try to come up with another solution.

**Comment by vBm** [comment]
@Stanzilla I've also tried what's suggested in 809 but doesn't help either.
However, this patch makes it work again.

**Comment by Stanzilla** [comment]
https://github.com/cmderdev/cmder/commit/567889e69fb00d7a3f7f661b8552916cb7e03a3d found it, paging @janschulz

**Comment by janschulz** [comment]
Unfortunately, I only send the patch, not found the cause: @vvartivarian-nbcu suggested the particular fix: https://github.com/cmderdev/cmder/issues/749#issuecomment-161407632

**Comment by janschulz** [comment]
But reading this: http://www.lua.org/manual/5.1/manual.html#pdf-io.popen it looks like the solution could never work: t returns a handle and not the exit code:

> io.popen (prog [, mode])
> Starts program prog in a separated process and returns a file handle that you can use to read data from this program (if mode is "r", the default) or to write data to this program (if mode is "w").
> This function is system dependent and is not available on all platforms.

**Comment by janschulz** [comment]
This might work: http://stackoverflow.com/a/14350308/1380673

**Comment by janschulz** [comment]
See also http://stackoverflow.com/questions/7607384/getting-return-status-and-program-output

this works:
```lua
---
 -- Get the status of working dir
 -- @return {bool}
---
function get_git_status()
    local file = io.popen("git diff --quiet --ignore-submodules HEAD 2>nul")
    -- This will get a table with some return stuff
    -- rc[3] will be the signal, 0 or 1
    local rc = {file:close()}
    return rc[3] == 0 
end
```

-> Will send a PR

**Comment by janschulz** [comment]
See https://github.com/cmderdev/cmder/pull/974 for the PR, please test... :-)

**Comment by sveggiani** [comment]
Closing this in favor of the more appropiate fix in #974

**Pull request closed without merging**
