### PR TITLE
v1.3 Release

### PR DESCRIPTION
**Pull request by MartiUK**
For when it's ready.

Will need manual merging.

## Add release notes below.

### CODE REVIEW

**Comment by Stanzilla** [comment]
We should probably start including the changelogs of the packages we bundle, in some way. 

a) Only highlight the issues that were fixed that people reported to us? (Lots of work)
b) just link to their changelogs
c) quote it all

What do you guys think?

**Comment by vladimir-kotikov** [comment]
@Stanzilla, you got me thinking about CHANGELOG, mine dont have one :smile:

**Comment by Stanzilla** [comment]
@vladimir-kotikov chop chop then!

**Comment by vladimir-kotikov** [comment]
Today.

**Comment by MartiUK** [comment]
I have a better idea.

**Pull request closed without merging**
