### PR TITLE
Compatible with Visual Studio Code (PowerShell)

### PR DESCRIPTION
**Pull request by gucong3000**
image

### CODE REVIEW

**Comment by gucong3000** [comment]
`config.json` of vscode
```json
{
    "terminal.integrated.shell.windows": "powershell.exe",
    "terminal.integrated.shellArgs.windows": [
        "-ExecutionPolicy",
        "Bypass",
        "-NoLogo",
        "-NoProfile",
        "-NoExit",
        "-Command",
        "Invoke-Expression '. ''D:\\Program Files\\cmder\\vendor\\profile.ps1'''"
    ]
}
```

**Comment by Stanzilla** [comment]
Hey sorry about that, but this has conflicts now

**Comment by Jackbennett** [comment]
Tested it on my vscode 1.17.2 and it works fine.

Adding a note, VScode defaults to powershell these days and personally my systems have the execution policy as  `remotesigned` so I only need;
```json
"terminal.integrated.shellArgs.windows": [
    "-noExit",
    "-command",
    "invoke-expression '. ''C:\\f\\src\\cmder\\vendor\\profile.ps1'''"
  ]
```

The string e

**Comment by chairchan** [comment]
"terminal.integrated.shell.windows": "powershell.exe",
    "terminal.integrated.shellArgs.windows": [
        "-ExecutionPolicy",
        "Bypass",
        "-NoLogo",
        "-NoProfile",
        "-NoExit",
        "-Command",
        "Invoke-Expression '. ''D:\\Cmder\\vendor\\profile.ps1'''"
    ]

**Comment by gucong3000** [comment]
@chairchan
https://stackoverflow.com/questions/35806066/missing-git-support-install-posh-git-with-install-module-posh-git-and-restart
http://www.cnblogs.com/HelloMyWorld/p/4119743.html

**Comment by chairchan** [comment]
@gucong3000  thank you, that works.
I have installed [posh-git](https://github.com/dahlbyk/posh-git) and everything works well.

**Comment by Dream4ever** [comment]
@gucong3000 Thank you very much, using posh-git and working very well in vscode!
Awesome!

**Pull request merged**
