### PR TITLE
Converting msysgit support to git-for-windows support.

### PR DESCRIPTION
**Pull request by Stanzilla**
Git for Windows is now final and we should probably ship with it. I renamed everything that I found that changed, the build scripts handles the portable release well, it's an 7zip installer now instead of an archive.

### CODE REVIEW

**Comment by JanSchulz** [comment]
This probably needs some path additions: https://github.com/bliker/cmder/issues/610

**Comment by Stanzilla** [comment]
Updated to https://github.com/git-for-windows/git/releases/tag/v2.5.1.windows.1

**Comment by DanielGGordon** [comment]
What else needs to be changed here?

**Comment by Stanzilla** [comment]
@DanielGGordon Nothing I know of, have you tested it? I released a build from my dev branch here https://github.com/Stanzilla/cmder/releases/tag/1.2.4

Otherwise, I think @MartiUK probably wants to test it out himself or just isn't in the mood of maintaining the project.

**Comment by DanielGGordon** [comment]
@Stanzilla I will test it today or tomorrow if it's ready. I think @MartiUK is pretty busy with some personal stuff. I think he wants to keep maintaining this project, but currently is having some trouble.

**Pull request merged**
