### PR TITLE
Updated the HG prompt

### PR DESCRIPTION
**Pull request by b0bh00d**
Per our email discussion, I have updated the HG prompt code to use the '-ib' option to 'hg id' so the branch name is always available, regardless of the state of the working copy.

### CODE REVIEW

**Comment by Stanzilla** [comment]
Thanks!

**Comment by Tomalak** [comment]
Just to throw this in here (cc @Stanzilla)

`hg id -ib` takes *significantly* longer than `hg branch` and `hg status` combined. 

```
D:\some\repo default
λ hg branch --time
default
time: real 0.016 secs (user 0.016+0.000 sys 0.000+0.000)

D:\some\repo default
λ hg status --time
M test.txt
time: real 0.037 secs (user 0.016+0.000 sys 0.016+0.000)
```

That's a total of 0.053 seconds, as opposed to

```
D:\some\repo default
λ hg id -ib --time
6242b58ed6c7+ default
time: real 0.251 secs (user 0.156+0.000 sys 0.094+0.000)
```

`hg id -ib` works, i.e. it gets the needed information, but it's awfully annoying to wait a 250ms-ish for every prompt. Maybe this isn't such a good way forward after all.

**Comment by Stanzilla** [comment]
=/ @b0bh00d

**Comment by b0bh00d** [comment]
On 1/18/2019 4:50 AM, Martin Böhm wrote:
>
> Just to throw this in here (cc @Stanzilla <https://github.com/Stanzilla>)
>
> |hg id -ib|takes /significantly/longer than |hg branch|and |hg status|combined.
>
> |D:\some\repo default λ hg branch --time default time: real 0.016 secs (user 
> 0.016+0.000 sys 0.000+0.000) D:\some\repo default λ hg status --time M 
> test.txt time: real 0.037 secs (user 0.016+0.000 sys 0.016+0.000) |
>
> That's a total of 0.053 seconds, as opposed to
>
> |D:\some\repo default λ hg id -ib --time 6242b58ed6c7+ default time: real 
> 0.251 secs (user 0.156+0.000 sys 0.094+0.000)|

|I ran the above commands using Mercurial version 4.7+11 on |||a "pristine" 
working copy with a 7.1GB disc footprint and more than 27,000 managed files. 
|Here's the result with some randomly modified files (and this is on an M.2 
drive):
|

    |λ hg branch --time|
    |default.bob.lwk|
    |time: real 0.005 secs (user 0.000+0.000 sys 0.000+0.000)|
    ||
    |λ hg status -q --time|
    |M Bootstrap.bat|
    |M LightWave\layout\layo.cpp|
    |M LightWave\layout\main.cpp|
    |M Purge.bat|
    ||
    |time: real 0.415 secs (user 0.344+0.000 sys 0.062+0.000)|
    ||
    |λ hg id -ib --time|
    |d61a2d50bfd4+ default.bob.lwk|
    |time: real 0.553 secs (user 0.438+0.000 sys 0.125+0.000)|
    ||

|I'd guess my repo is considerably larger than yours, which accounts for the 
much larger overhead of time on "hg status."

Without any modified or unmanaged files in the repo, the "quiet" version of 
"hg status" takes much less time on my system:
|

    |λ hg status -q --time|
    ||
    |time: real 0.242 secs (user 0.125+0.000 sys 0.109+0.000)|
    ||

|However, if I remove the "quite" option, the time surprisingly skyrockets on 
a "pristine" working copy:
|

    |λ hg status --time|
    ||
    |time: real 0.586 secs (user 0.531+0.000 sys 0.047+0.000)|
    ||

|"hg id" does indeed take more time, but I only have a difference of 0.133 
between them using your commands. Additionally, the Lua code is only running 
one command instead of two, which would I suppose double the execution 
overhead, if we're counting milliseconds.  It probably wouldn't add much, but 
it would certainly reduce the difference by some amount.


|||||
>
> |hg id -ib| works, i.e. it gets the needed information, but it's awfully 
> annoying to wait a 250ms-ish for every prompt. Maybe this isn't such a good 
> way forward after all.
>

|I'd love to have the speed of git, but Mercurial simply doesn't have it.  If 
100-200 milliseconds really means that much, then it can certainly be switched 
to use the branch/status command pair instead.  Just tell me if that's what 
you want.

|

**Pull request merged**
