### PR TITLE
User conemu cfg

### PR DESCRIPTION
**Pull request by daxgames**
- Allows user to have a .config/user-conemu.xml file that is not %COMPUTERNAME% specific.
- Backs up the ./vendor/conemu-maximus5/conemu.xml file if it exist at startup to ./config/ConEmu-%COMPUTERNAME%.xml OR ./config/user-ConEmu.xml if one or the other already exists in that order.  If neither exists the backup will default to ./config/user-ConEmu.xml this maintains a portable copy of changes made to this file while using cmder.

### CODE REVIEW

**Comment by daxgames** [comment]
I do not like having to have a computer name in my custom config file that I want to be the same on all hosts.

@kodybrown when I added the user-ConEmu.xml check after your computer specific check I removed some code, lines 129-132.  I could not see that these lines actually did anything used by the cmder launcher.

Will this break your situation somehow?

**Comment by kodybrown** [comment]
You should be fine. Line 129 simply converts Envars to the real path. And, the other lines were to provide a way to get the 'normal' settings file if there wasn't a machine-specific version. Yeah, I think its fine.

**Comment by daxgames** [comment]
@kodybrown any comments on my add of backing up of the customized config file?  I hated that my ongoing 'conemu.xml' customizations were lost of I deleted the vendor folder for a fresh install.

This is nice since it backs up the continually changing 'conemu.xml' file to a computer named file (if it exists in ./config/) or user file if not at cmder launch.

**Comment by daxgames** [comment]
Bump.  Has anyone on the Cmder core team looked at this?  

* This provides a check for a custom user-ConEmu.xml storage that will serve as a user custom default config for any system '%cmder_root%/config' is copied to for new installs.
'%cmder_root%/vendor/ConEmu-Maximus5/ConEmu.xml' is maintained as the config file used for all sessions.
* Possible loss of ongoing changes to '%cmder_root%/vendor/ConEmu-Maximus5/ConEmu.xml' are mitigated by the backup of the last saved settings to the '%cmder_root%/config/' folder .
* Custom config based on computer name is too specific for most users but some have this use case so it still works.

**Comment by MartiUK** [comment]
Sorry Dax, I'll look into it more tomorrow.

**Comment by daxgames** [comment]
No problem, was just wondering if there were questions.

**Comment by MartiUK** [comment]
It looks fine after a first glance, will need to check the launcher code more thoroughly.

**Comment by daxgames** [comment]
Ok I did compile and test it with Visual Studio Community Edition 2015.  It works in all situations  and it does work but I am no c++ guru so that would be good.

**Comment by Stanzilla** [comment]
@daxgames the checks here froze for whatever reason, can you push something to re-trigger them?

**Comment by MartiUK** [comment]
@Stanzilla I've removed that one check, that was preventing merges.

**Comment by Stanzilla** [comment]
@MartiUK alright, we also need a decision on which branch to use going forward, still dev and master for releases or all master.

**Comment by daxgames** [comment]
I can push it again as soon as my system comes back up.

**Comment by daxgames** [comment]
Pushed, hopefully this allows checks to complete.

**Pull request merged**
