### PR TITLE
Fix git branch colouring

### PR DESCRIPTION
**Pull request by MoFo88**
More elegant way of detecting changes in git repo.
***
Second pull request to a proper branch per @Stanzilla request.

### CODE REVIEW

**Comment by janschulz** [comment]
LGTM!

A `git rebase origin/development` could help to get rid of the merge commit.

**Comment by MoFo88** [comment]
I did rebase on my `development` branch as well as rebase of this feature branch. Should be fine now.

**Comment by vBm** [comment]
I must say I don't like this because even untracked files are now triggering color change :-1: 
Maybe this is the correct way of doing coloring but you know xD

**Comment by MoFo88** [comment]
Can be easily changed, to exclude untracked files. The question is what is the correct behaviour here. Not sure who decides here...

**Comment by Stanzilla** [comment]
Hrm, green for clean, yellow for untracked files, red for untracked files and changes?

**Comment by MoFo88** [comment]
Sounds like a plan, but I would leave the default font colour for clean repo.

**Comment by Stanzilla** [comment]
Yeah probably saner

**Pull request merged**
