### PR TITLE
Added rainbow colored icons

### LINKED ISSUE #947: Provide alternate icon colors
Sample use case: I have a bunch of different environments at work, and it's super useful to have a different color-coded CMD window for each. Color-shifted versions of https://github.com/cmderdev/cmder/blob/master/icons/cmder.ico would be great.

*(I'll send a PR shortly)*

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #947

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
Note that it's about 1.4 MB extra on disk, if you're ok with that.

**Comment by Stanzilla** [comment]
fine by me, @cmderdev/trusted-contributors?

**Comment by Jackbennett** [comment]
Those look nice, I have no problem with this, it's @cmderdev/core 's baby.

**Comment by MartiUK** [comment]
You might need to add the new files to packignore, so they'll be included when cmder is packaged.

**Comment by JoshuaKGoldberg** [comment]
@MartiUK added in da9517d91f477dae84147dfdf59d1ea86d001ea3

**Comment by JoshuaKGoldberg** [comment]
On the file size issue: the original .ico is 17.6 KB while the colored ones are all 147 KB. What program did you use to make it?

**Comment by MartiUK** [comment]
That would be a question for @bliker as he originally designed the logo, I can have a guess and say he probably saved it with a smaller colour depth i.e. 4bpp.

**Comment by MartiUK** [comment]
@JoshuaKGoldberg are you looking at reducing the size of the .ico files?

**Comment by Jackbennett** [comment]
You can at least run the png's through an optimizer to get like 90% off each one.

**Comment by JoshuaKGoldberg** [comment]
@MartiUK @Jackbennett finally got around to compressing them.

**Comment by Stanzilla** [comment]
@JoshuaKGoldberg can you PR that into the development branch, please?

**Pull request closed without merging**
