### PR TITLE
Update clink to 1.2.22

### PR DESCRIPTION
**Pull request by AltarBeastiful**
Latest update of clink contains some interesting changes. 
Mainly the ability to [complete on doskey aliases ](https://github.com/chrisant996/clink/issues/119)

### CODE REVIEW

**Comment by chrisant996** [comment]
I recommend updating to Clink v1.2.22 when it gets released in the next day or two.
Some highlights:
- Git prompt does its expensive work in the background, nearly eliminating the "prompt lag".
- New `clink-select-complete` command that has Powershell-like and Fish-like interactive completion.
- Shift+arrow keys select input text, typing replaces selection, etc.
- Argmatchers for commands work even in doskey aliases that use the commands.
- Many bug fixes since the v1.1.45 Cmder currently includes.
- v1.2.22 will complete a major milestone, and finish the planned feature work for a while.

**Comment by chrisant996** [comment]
Clink v1.2.22 has been released.  I recommend updating Cmder to include that instead of 1.2.20, because it includes a few additional fixes and features.

**Comment by AltarBeastiful** [comment]
Updated PR with latest version as proposed

**Comment by chrisant996** [comment]
Clink v1.2.23 includes two minor fixes, sorry.  Not a big deal if it's not picked up in the next Cmder yet, but <kbd>PgDn</kbd> could behave strangely in `clink-select-complete`, and a purely cosmetic change for the key name for <kbd>Ctrl</kbd>+<kbd>M</kbd> when `terminal.differentiate_keys` was false.

**Pull request merged**
