### PR TITLE
Compatible with Visual Studio Code (cmd)

### PR DESCRIPTION
**Pull request by gucong3000**
image

### CODE REVIEW

**Comment by gucong3000** [comment]
`config.json` of vscode
```json
{
    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "D:\\Program Files\\cmder\\vendor\\init.bat"
    ]
}
```

**Comment by Stanzilla** [comment]
Can you explain why this is needed, please?

**Comment by gucong3000** [comment]
Without is PR, vscode can not use cmder.

**Comment by gucong3000** [comment]
And it will work for other IDEs.

**Comment by gucong3000** [comment]
#1417

**Comment by gucong3000** [comment]
What can I do for help?

**Pull request merged**
