### PR TITLE
simplified λ prompt in lua

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
The lambda (λ) character for the prompt is defined only once instead of twice, making it easy for customizations to change shell handle character.

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
@daxgames You might want to squash and merge this, because of the sloppy commits.

**Comment by DRSDavidSoft** [comment]
Related issues: #1688 #1261 #104 
Also on another note, I know λ is an iconic part of Cmder, but an option for the user to customize it would be nice.

**Comment by DRSDavidSoft** [comment]
@Stanzilla is this able to merge? I want to work on  another branch to customize the prompt character and color.

**Comment by Stanzilla** [comment]
Yup, looks good, thanks for that! Wonder why I never changed it...

**Pull request merged**
