### PR TITLE
Add `/x "CONEMU ARGS"` command line argument.

### PR DESCRIPTION
**Pull request by eziosella**
This argument forwards parameters to ConEmu app.

	e.g. Cmder.exe /FWPARS "-min -tsa"

In this case Cmder will start minimized on TaskBar

### CODE REVIEW

**Comment by daxgames** [comment]
Thanks for the PR,  I have not looked yet but will look later today when i get home.  Initial thoughts and questions:

1. Is the arg case sensitive?  Hopefully not.

2.  Did you update the command line help?

3.  Did you update the `README.md` with documentation.

4. Can you make the arg `/conemu`, seems more intuitive.

The issue I forsee is what if a conemu arg needs to be quoted.

**Comment by eziosella** [comment]
Hi All,
below my replies:


  *   1. Is the arg case sensitive? Hopefully not.
  *   No It is not.
  *   2. Did you update the command line help?
  *   Yes I did.
  *   3. Did you update the README.md with documentation
  *   Yes. I did.
  *   4. Can you make the arg /conemu, seems more intuitive
  *   Yes OK. It seems better and more intuitive.


About the quoted conemu args I did not go in deeper but it dosen’t seem it has for now.

Regards
Ezio

Da: Dax T Games <notifications@github.com>
Inviato: domenica 12 maggio 2019 16:15
A: cmderdev/cmder <cmder@noreply.github.com>
Cc: Ezio Sella <E.Sella@bdfdigital.it>; Author <author@noreply.github.com>
Oggetto: Re: [cmderdev/cmder] Add FWPARS cmdline argument. (#2096)


Thanks for the PR, I have not looked yet but will look later today when i get home. Initial thoughts and questions:

  1.  Is the arg case sensitive? Hopefully not.
  2.  Did you update the command line help?
  3.  Did you update the README.md with documentation.
  4.  Can you make the arg /conemu, seems more intuitive.

The issue I forsee is what if a conemu arg needs to be quoted.

**Comment by eziosella** [comment]
OK I will.

Bye

Da: Dax T Games <notifications@github.com>
Inviato: domenica 12 maggio 2019 18:03
A: cmderdev/cmder <cmder@noreply.github.com>
Cc: Ezio Sella <E.Sella@bdfdigital.it>; Author <author@noreply.github.com>
Oggetto: Re: [cmderdev/cmder] Add FWPARS cmdline argument. (#2096)


@daxgames requested changes on this pull request.

I have compiled and tested it here.

Please change the parameter to /conemu-args so it is more intuitive and add to the Unreleased section of the CHANGELOG.md usint the same format that is used there.

**Comment by daxgames** [comment]
@eziosella I hope I did not discourage your participation by asking for changes.  You still working on this?  Or did you decide to tackle the quoting question I raised or maybe the forward all unknown args direct to conemu?

You could just make this argument be `/x`.  It's short, could mean 'extra parameters'.  I've been thinking about it and `/fwpars` and `/conemu-args` are just too long.

**Comment by eziosella** [comment]
@daxgames No discouraged, just been busy.

About the `/x` argument it is definitely better. I already had modified (not pushed yet) with `/conemu-args` but i will change for the shorter way.

**Comment by daxgames** [comment]
@eziosella MERGED.  Thanks again for the PR  and the changes.

**Pull request merged**
