### PR TITLE
Use Github Actions to build and release

### LINKED ISSUE #2723: Cmder build is failing
@cmderdev/core @cmderdev/trusted-contributors anyone know how to fix this.

image

### LINKED ISSUE #2729: Create MSI Package
A common request is to create a non-portable installer for cmder, this issue encompasses this.

I suggest we look at creating an MSI so we can add cmder to winget also.

### PR DESCRIPTION
**Pull request by MartiUK**
Fixes #2723
Fixes #2729

### CODE REVIEW

**Comment by daxgames** [comment]
Did Appveyor discontinue some part of their service offering that broke this?

**Comment by MartiUK** [comment]
Looking into it but yeah it's likely they don't install the older platform tools now

**Comment by MartiUK** [comment]
That would be my preference too

**Comment by daxgames** [comment]
@MartiUK  @Stanzilla  Hey guys do either of you know the secret sauce to be able to compile the launcher locally on Windows running VS Community(any version).  

I have never been able to  use `scripts\build.ps1:

image

I figured out on an old windows install with VS Community 2017 but I am getting the below when I try now with Visual Studio Community 2022:

image

Asking here because I hope you guys can save me time of digging to figure it out again.

**Comment by Stanzilla** [comment]
I haven't done that in ages but your first error message looks like you are missing or having a wrong version of the Windows SDK?

Also I faintly remember that I did not use build.ps1 but just hit compile in VS

**Comment by daxgames** [comment]
@stanzilla I actially found my old laptop that has vs community 2019 on it and both script and gui work fine.

No such luck with vs community 2022 even though it appears I have all SDK installed correctly.  Probably missing one small piece.

Thanks for the reply.

**Comment by daxgames** [comment]
@Stanzilla I figured out how to get it to build on VS Comunity 2022.  

I had to change the platform tools in the UI to something then change them back to the original.  This allows it to build in the UI.

Then for `scripts/build.ps1` to work I had to open the `x64 Native Tools Command Prompt for VS 2022` Start Menu shortcut, run powershell, then run `scripts/build.ps1 -compile` .

Initially I was launching the `Developer PowerShell for VS 2022` Start menu shortcut and running  `scripts/build.ps1 -compile` which failed with the windows.h not found error.

I am obviously not a proficient Visual Studio user!  👍

**Comment by MartiUK** [comment]
I've been busy with work recently but I was working on the build scripts as well to work with the latest Windows SDK

**Comment by DRSDavidSoft** [comment]
@MartiUK I added an initial GitHub Actions workflow to build Cmder using GitHub, however there are some [known limitations](https://github.com/actions/upload-artifact#limitations) regarding artifacts (e.g. it seems that [zipped artificats](https://github.com/actions/upload-artifact#zipped-artifact-downloads)) are doubly created, i.e. once by Cmder build scripts and one more time by GitHub actions)

**Update 2026:** Fixed in #3075

**Pull request merged**
